---
# Source: fiap-pedidos/templates/db/service.yaml
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: mysql-fiap
  namespace: default
  labels:
    app: mysql-fiap
spec:
  selector:
    app: mysql-fiap
  ports:
  - name: mysql-fiap
    protocol: TCP
    port: 3306
    targetPort: 3306
