on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compute revision
        id: revision
        run: echo "sha_short=v$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
  
      - name: Build Docker Image
        run: docker build -t pedidos-service-tech-challenge:${{ steps.revision.outputs.sha_short }} .

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          project_id: ${{vars.PROJECT_ID}}
          service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
          export_default_credentials: true

      - name: Auth gcloud docker
        run: gcloud auth configure-docker

      - name: Push docker image to gcp container registry
        env:
          REVISION: 2.1
        run: |-
          docker tag pedidos-service-tech-challenge:${{ steps.revision.outputs.sha_short }} gcr.io/${{vars.PROJECT_ID}}/pedidos-service-tech-challenge:${{ steps.revision.outputs.sha_short }}
          docker push gcr.io/${{vars.PROJECT_ID}}/pedidos-service-tech-challenge:${{ steps.revision.outputs.sha_short }}

      - name: Deploy to CloudRun
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{vars.SERVICE_NAME}}
          image: gcr.io/${{vars.PROJECT_ID}}/pedidos-service-tech-challenge:${{ steps.revision.outputs.sha_short }}
          region: ${{vars.DEPLOY_REGION}}
