on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
  
      - name: Build Docker Image
        run: docker build -t pedidos-service-tech-challenge:1.0 .
        # working-directory: ./fiap-tech-challenge-1-pedidos

      # - name: Google Auth
      #   uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: ${{secrets.WIF_PROVIDER}}
      #     service_account: ${{WIF_SERVICE_ACCOUNT}}

      - name: Configure GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: fiap-tech-challenge-403000
          service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
          export_default_credentials: true

      # - name: Docker Auth
      #   run: gcloud auth configure-docker
