on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./fiap-tech-challenge-1-pedidos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

    # - name: Build
    #   run: npm run build
  
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
  
      - name: Build Docker Image
        run: docker build -t pedidos-service-tech-challenge:1.0 .
        working-directory: ./fiap-tech-challenge-1-pedidos
